import {
  Type,
  Mail,
  Hash,
  FileText,
  ChevronDown,
  Circle,
  CheckSquare,
  Calendar,
  Upload,
  Plus,
} from "lucide-react";

export const formfields = [
  {
    name: "text",
    label: "Text",
    type: "text",
    icon: Type,
    color: "bg-blue-50 border-blue-200 hover:bg-blue-100",
  },
  {
    name: "email",
    label: "Email",
    type: "email",
    icon: Mail,
    color: "bg-green-50 border-green-200 hover:bg-green-100",
  },
  {
    name: "number",
    label: "Number",
    type: "number",
    icon: Hash,
    color: "bg-purple-50 border-purple-200 hover:bg-purple-100",
  },
  {
    name: "textarea",
    label: "Textarea",
    type: "textarea",
    icon: FileText,
    color: "bg-orange-50 border-orange-200 hover:bg-orange-100",
  },
  {
    name: "dropdown",
    label: "Dropdown",
    type: "dropdown",
    icon: ChevronDown,
    color: "bg-indigo-50 border-indigo-200 hover:bg-indigo-100",
  },
  {
    name: "radio_buttons",
    label: "Radio Buttons",
    type: "radio_buttons",
    icon: Circle,
    color: "bg-pink-50 border-pink-200 hover:bg-pink-100",
  },
  {
    name: "checkbox",
    label: "Checkbox",
    type: "checkbox",
    icon: CheckSquare,
    color: "bg-teal-50 border-teal-200 hover:bg-teal-100",
  },
  {
    name: "date_picker",
    label: "Date Picker",
    type: "date_picker",
    icon: Calendar,
    color: "bg-red-50 border-red-200 hover:bg-red-100",
  },
  {
    name: "file_upload",
    label: "File Upload",
    type: "file_upload",
    icon: Upload,
    color: "bg-yellow-50 border-yellow-200 hover:bg-yellow-100",
  },
];
