import {
  Type,
  Mail,
  Hash,
  FileText,
  ChevronDown,
  Circle,
  CheckSquare,
  Calendar,
  Upload,
  Plus,
  Heading,
} from "lucide-react";
import { Field } from "../interfaces/types";
import { pl } from "date-fns/locale";

export const formfields = [
  {
    name: "Text",
    label: "Text",
    type: "text",
    icon: Type,
    color: "bg-blue-50 border-blue-200 hover:bg-blue-100",
    placeholder: "Enter text",
  },
  {
    name: "Email",
    label: "Email",
    type: "email",
    icon: Mail,
    color: "bg-green-50 border-green-200 hover:bg-green-100",
    placeholder: "Enter an email",
  },
  {
    name: "Number",
    label: "Number",
    type: "number",
    icon: Hash,
    color: "bg-purple-50 border-purple-200 hover:bg-purple-100",
    placeholder: "Enter a number",
  },
  {
    name: "Textarea",
    label: "Textarea",
    type: "textarea",
    icon: FileText,
    color: "bg-orange-50 border-orange-200 hover:bg-orange-100",
    placeholder: "Enter text",
  },
  {
    name: "Dropdown",
    label: "Dropdown",
    type: "dropdown",
    icon: ChevronDown,
    color: "bg-indigo-50 border-indigo-200 hover:bg-indigo-100",
    options: ["Option 1", "Option 2", "Option 3"],
    placeholder: "Select an option",
  },
  {
    name: "Radio Buttons",
    label: "Radio Buttons",
    type: "radio_buttons",
    icon: Circle,
    color: "bg-pink-50 border-pink-200 hover:bg-pink-100",
    options: ["Option 1", "Option 2", "Option 3"],
    placeholder: "Select an option",
  },
  {
    name: "Checkbox",
    label: "Checkbox",
    type: "checkbox",
    icon: CheckSquare,
    color: "bg-teal-50 border-teal-200 hover:bg-teal-100",
    options: ["Option 1", "Option 2", "Option 3"],
    placeholder: "Select an option",
  },
  {
    name: "Date Picker",
    label: "Date Picker",
    type: "date_picker",
    icon: Calendar,
    color: "bg-red-50 border-red-200 hover:bg-red-100",
    placeholder: "Select a date",
  },
  {
    name: "File Upload",
    label: "File Upload",
    type: "file_upload",
    icon: Upload,
    color: "bg-yellow-50 border-yellow-200 hover:bg-yellow-100",
  },
  {
    name: "Heading",
    label: "Heading",
    type: "heading",
    icon: Heading,
    color: "bg-gray-50 border-gray-200 hover:bg-gray-100",
    placeholder: "Enter sub heading",
    value: "",
    size: {
      heading_size: "20",
      sub_heading_size: "18",
    },
    alignment: "start",
  },
];
